---
title: "Peak sum plot"
author: "Beth Moore"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```{r install}
install.packages("BiocManager")
install.packages("viridis")
if(!require(devtools)) install.packages("devtools")
devtools::install_github("kassambara/ggpubr")
BiocManager::install("chromVAR")
BiocManager::install("GenomicRanges")
```
```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(reticulate)
use_condaenv("/w5home/bmoore/miniconda3/envs/cut_tag")
library(rmarkdown)
library(ggplot2)
library(tidyverse)
library(stringr)
library(viridis)
library(ggpubr)
library(corrplot)
library(GenomicRanges)
library(chromVAR)
projPath = "/w5home/rmillikin/sequencing/kratz/2024-06-14-cuttag/output_dir"
sampleList = c("Brd4", "H3K27me3", "H3K4me3", "H3K27ac", "H3K4me1", "pRBP1_CTD")
histList = c("Brd4", "H3K27me3", "H3K4me3", "H3K27ac", "H3K4me1", "pRBP1_CTD")
setwd(projPath)
```

# Number of peaks called
```{r peak_sum}
peakN = c()
peakWidth = c()
#peakType = c("control", "top0.01")
for(hist in sampleList){
  histInfo = hist#strsplit(hist, ".")[[1]]
  if(histInfo[1] != "IgG"){
    #for(type in peakType){
      peakInfo = read.table(paste0(projPath, "/peakCalling/SEACR/", hist, "_seacr.peaks.relaxed.bed"), header = FALSE, fill = TRUE)  %>% mutate(width = abs(V3-V2))
      peakN = data.frame(peakN = nrow(peakInfo), peakType = "relaxed0.4", Histone = histInfo[1], Replicate = histInfo[2]) %>% rbind(peakN, .)
      peakWidth = data.frame(width = peakInfo$width, peakType = "relaxed0.4", Histone = histInfo[1], Replicate = histInfo[2])  %>% rbind(peakWidth, .)
    #}
  }
}
peakN %>% select(Histone, Replicate, peakType, peakN)
```
# Reproducibility of the peak across biological replicates
```{r reproducibility}
# no need to run if no replicates
# The reproducibility is calculated by
# peaks overlapping rep1 and rep2/# peaks of rep1 or rep2 * 100


#repL = paste0("rep", 1:2)
peakType = "relaxed0.4" #c("control", "top0.01")
peakOverlap = c()
for(type in peakType){
  for(hist in histList){
    overlap.gr = GRanges()
    #for(rep in repL){
      peakInfo = read.table(paste0(projPath, "/peakCalling/SEACR/", hist,"_seacr.peaks.relaxed.bed"), header = FALSE, fill = TRUE)
      peakInfo.gr = GRanges(peakInfo$V1, IRanges(start = peakInfo$V2, end = peakInfo$V3), strand = "*")
      if(length(overlap.gr) >0){
        overlap.gr = overlap.gr[findOverlaps(overlap.gr, peakInfo.gr)@from]
      }else{
        overlap.gr = peakInfo.gr
        
      }
    #}
    peakOverlap = data.frame(peakReprod = length(overlap.gr), Histone = hist, peakType = type) %>% rbind(peakOverlap, .)
  }
}

peakReprod = left_join(peakN, peakOverlap, by = c("Histone", "peakType")) %>% mutate(peakReprodRate = peakReprod/peakN * 100)
peakReprod %>% select(Histone, Replicate, peakType, peakN, peakReprodNum = peakReprod, peakReprodRate)
```

# Calculate FRIPs: FRagment proportion in Peaks regions, as a measure of signal-to-noise
```{r frips}
library(chromVAR)

bamDir = paste0(projPath, "/alignment/bam")
inPeakData = c()
#histL = c("H3K27me3", "H3K36me3")
## overlap with bam file to get count
for(hist in histList){
  #for(rep in repL){
    peakRes = read.table(paste0(projPath, "/peakCalling/SEACR/", hist, "_seacr.peaks.relaxed.bed"), header = FALSE, fill = TRUE)
    peak.gr = GRanges(seqnames = peakRes$V1, IRanges(start = peakRes$V2, end = peakRes$V3), strand = "*")
    bamFile = paste0(bamDir, "/", hist, "_bowtie2.mapped.bam")
    fragment_counts <- getCounts(bamFile, peak.gr, paired = TRUE, by_rg = FALSE, format = "bam")
    inPeakN = counts(fragment_counts)[,1] %>% sum
    inPeakData = rbind(inPeakData, data.frame(inPeakN = inPeakN, Histone = hist)) # , Replicate = rep
  #}
}

frip = left_join(inPeakData, alignResult, by = "Histone") %>% mutate(frip = inPeakN/MappedFragNum_axl * 100) # c("Histone", "Replicate"))
frip %>% select(Histone, SequencingDepth, MappedFragNum_axl, AlignmentRate_axl, FragInPeakNum = inPeakN, FRiPs = frip) # Replicate, 
```

```{r visualize}
fig7A = peakN %>% ggplot(aes(x = Histone, y = peakN, fill = Histone)) +
    geom_boxplot() +
    #geom_jitter(aes(color = Replicate), position = position_jitter(0.15)) +
    facet_grid(~peakType) +
    scale_fill_viridis(discrete = TRUE, begin = 0.1, end = 0.55, option = "magma", alpha = 0.8) +
    scale_color_viridis(discrete = TRUE, begin = 0.1, end = 0.9) +
    theme_bw(base_size = 18) +
    ylab("Number of Peaks") +
    xlab("") +
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

fig7B = peakWidth %>% ggplot(aes(x = Histone, y = width, fill = Histone)) +
    geom_violin() +
    #facet_grid(Replicate~peakType) +
    scale_fill_viridis(discrete = TRUE, begin = 0.1, end = 0.55, option = "magma", alpha = 0.8) +
    scale_color_viridis(discrete = TRUE, begin = 0.1, end = 0.9) +
    scale_y_continuous(trans = "log", breaks = c(400, 3000, 22000)) +
    theme_bw(base_size = 18) +
    ylab("Width of Peaks") +
    xlab("") + 
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

fig7C = peakReprod %>% ggplot(aes(x = Histone, y = peakReprodRate, fill = Histone, label = round(peakReprodRate, 2))) +
    geom_bar(stat = "identity") +
    geom_text(vjust = 0.1) +
    #facet_grid(Replicate~peakType) +
    scale_fill_viridis(discrete = TRUE, begin = 0.1, end = 0.55, option = "magma", alpha = 0.8) +
    scale_color_viridis(discrete = TRUE, begin = 0.1, end = 0.9) +
    theme_bw(base_size = 18) +
    ylab("% of Peaks Reproduced") +
    xlab("") + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

fig7D = frip %>% ggplot(aes(x = Histone, y = frip, fill = Histone, label = round(frip, 2))) +
    geom_boxplot() +
    #geom_jitter(aes(color = Replicate), position = position_jitter(0.15)) +
    scale_fill_viridis(discrete = TRUE, begin = 0.1, end = 0.55, option = "magma", alpha = 0.8) +
    scale_color_viridis(discrete = TRUE, begin = 0.1, end = 0.9) +
    theme_bw(base_size = 18) +
    ylab("% of Fragments in Peaks") +
    xlab("") + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

pdf(file= "peak_plots.pdf", width=7, height=7)
ggarrange(fig7A, fig7B, fig7C, fig7D, ncol = 2, nrow=2, common.legend = TRUE, legend="bottom")
dev.off()
```